import { Navbar } from "../components/Navbar";
import { Rail } from "../components/Rail";
import { Filemanager } from "../components/Filemanager";
import { Editor } from "../components/Editor";
import "./globals.css";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body className="flex h-screen flex-col bg-black text-neutral-300 antialiased">
        <header>
          <Navbar />
        </header>
        <main className="flex grow">
          <Rail />
          <Filemanager />
          <Editor content={children} />
        </main>
        <footer className="border-t border-neutral-800 bg-neutral-800 p-1 text-xs">
          status{" "}
        </footer>
      </body>
    </html>
  );
}
